### ISSUE TITLE
report kang

### ISSUE THREAD

**Issue by yEsPaP** [davinash97/J7#2]

**Comment by davinash97** [comment]
where kang, send link

**Comment by yEsPaP** [comment]
> where kang, send link

https://github.com/yEsPaP/M105G/commit/73993911953b9fed827a29394683dc4d9097f2e8

**Comment by davinash97** [comment]
404

**Comment by yEsPaP** [comment]
> 404

lies. opens fine for me

**Comment by davinash97** [comment]
truth cause it never exist
